qiskit-community/ffsim

python/ffsim/gates/orbital_rotation.py, src/gates/orbital_rotation.rs
Use `arg` to compute complex angle instead of dividing by norm, which was causing a NaNs due to division by zero.
Fixes #95
=> Fix Rust orbital rotation numerical instability

python/ffsim/variational/ucj.py, tests/variational/ucj_test.py
For consistency with `MolecularData` and pyscf.
=> rename t2_amplitudes and t1_amplitudes to t2 and t1

python/ffsim/gates/orbital_rotation.py, python/ffsim/linalg/__init__.py, python/ffsim/linalg/givens.py, tests/python/linalg/givens_test.py
Fixes #34.
Changes the description of a Givens rotation to be a flat tuple `(c, s, i, j)` instead of `((c, s), (i, j))`, which is a breaking change.
=> Document Givens decomposition

pyproject.toml, python/ffsim/__init__.py, python/ffsim/qiskit/__init__.py, python/ffsim/qiskit/orbital_rotation.py, python/ffsim/qiskit/util.py, tests/python/qiskit/__init__.py, tests/python/qiskit/orbital_rotation_test.py, tests/python/qiskit/util_test.py
- Create `ffsim.qiskit` module for code to construct quantum circuits.
- Add `OrbitalRotationJW` gate.
- Add `qiskit` as a dependency.
=> Add ffsim.qiskit module and OrbitalRotationJW gate

pyproject.toml
It's recommended that tox be installed in an isolated environment, see e.g. https://tox.wiki/en/4.14.2/installation.html
=> Remove tox as dev dependency since it should be installed in an isolated environment

docs/how-to-guides/entanglement-forging.ipynb, docs/how-to-guides/fermion-operator.ipynb, docs/how-to-guides/index.md, docs/how-to-guides/lucj.ipynb, docs/index.md, docs/tutorials/02-orbital-rotation.ipynb, docs/tutorials/03-double-factorized.ipynb, docs/tutorials/index.md, src/fermion_operator.rs
Rebrand some of the tutorials as how-to guides
=> reorganize docs

python/ffsim/operators/fermi_hubbard.py, tests/python/operators/fermi_hubbard_test.py
This PR fixes an edge case in fermi_hubbard_1d, which appears when the number of spatial orbitals N=2, and periodic boundary conditions are set (i.e. a ring with two sites). In this case, the hopping due to the periodic boundary conditions has the same dictionary key as the internal hopping. Instead of this dictionary key being overwritten, it should be added.
=> Fix edge case in fermi_hubbard_1d

python/ffsim/qiskit/slater_determinant.py, tests/python/qiskit/slater_determinant_test.py
Changes the API of SlaterDeterminantJW to match the slater_determinant function. In particular, it accepts occupied orbitals and a full orbital rotation matrix, instead of just a subset of the orbital rotation matrix containing the columns for the desired orbitals.
=> Change SlaterDeterminantJW API to match slater_determinant function

python/ffsim/gates/basic_gates.py, python/ffsim/gates/diag_coulomb.py, python/ffsim/gates/num_op_sum.py, python/ffsim/gates/orbital_rotation.py, python/ffsim/qiskit/sim.py, python/ffsim/variational/givens.py, tests/python/_slow/gates/diag_coulomb_test.py, tests/python/gates/num_op_sum_test.py
It has a non-negligible impact on performance. Validation should be done at a higher level (e.g. it's still done for the Qiskit gates).
=> remove input validation for low-level gates

pyproject.toml
In 2.3, the following code crashes with `zsh: floating point exception`:
```python
from pyscf.fci import cistring
linkstr_index_a = cistring.gen_linkstr_index(range(23), 3)
```
=> increase pyscf requirement to 2.4

python/ffsim/variational/ucj_spin_balanced.py, python/ffsim/variational/ucj_spin_unbalanced.py, python/ffsim/variational/ucj_spinless.py, tests/python/variational/ucj_spin_balanced_test.py, tests/python/variational/ucj_spin_unbalanced_test.py, tests/python/variational/ucj_spinless_test.py
=> Validate UCJ dataclasses

python/ffsim/molecular_data.py, tests/python/molecular_data_test.py
in MolecularData. It doesn't work if the SCF object doesn't have all its properties initialized, such as when it's initialized using `pyscf.tools.fcidump.to_scf`.
=> don't attempt to compute dipole integrals and orbital symmetries

python/ffsim/molecular_data.py
This works for an SCF that was loaded from an FCIDUMP file. See https://github.com/pyscf/pyscf/issues/2303.
=> use nao instead of nao_nr()

pyproject.toml, python/ffsim/hamiltonians/molecular_hamiltonian.py, tests/python/hamiltonians/molecular_hamiltonian_test.py, tests/python/hamiltonians/single_factorized_hamiltonian_test.py
Fixes #81 
This needs to wait for the next release of PySCF (after 2.6.2).
=> Support complex two-body tensor linear operator

python/ffsim/random/random.py, tests/python/random_test.py
Also fixes the documentation of random density matrix to give a correct definition.
=> Sample random states: raise ValueError if dim is zero

python/ffsim/qiskit/jordan_wigner.py, tests/python/qiskit/jordan_wigner_test.py
Fixes #373 .
Originally, I envisioned `n_qubits` allowing the user to pad the operator with extra qubits. I don't see an actual use case for this though, and #373 shows that it's more important to be able to specify the actual number of orbitals. In the new code, the number of qubits is always twice the number of spatial orbitals. If necessary, the user can pad with extra qubits in post-processing.
=> Replace n_qubits argument in ffsim.qiskit.jordan_wigner with norb

pyproject.toml, python/ffsim/molecular_data.py
=> delete _remove_sym_from_fcidump PySCF hack

python/ffsim/__init__.py, python/ffsim/states/__init__.py, python/ffsim/states/rdm.py, tests/python/states/rdm_test.py
This class stores spin-summed one- and two-body density matrix. The following methods are provided:
- `rotated`: For applying an orbital rotation to the reduced density matrices.
- `expectation`: For computing the expectation value with a MolecularHamiltonian.
=> Add ReducedDensityMatrix class

python/ffsim/qiskit/sim.py, tests/python/qiskit/sim_test.py
Part of #369 
This PR adds support for Qiskit's `CCZGate` and `CRZGate` to the fermionic simulator.
Added unit-tests accordingly.
- For spinless circuits, three qubits indices `(i, j, k)` are mapped to spatial orbitals. This applies
$$U_{CCZ} = exp(i \pi n_i n_j n_k)$$
- For spinful circuits, qubit indices are mapped to a pair of lists `(S_α, S_β)`. This applies
$$ U_{CCZ} = exp\left(i \pi \prod_{p \in S_\alpha} n_{\alpha, p} \prod_{q \in S_\beta} n_{\beta,q}\right)$$
- For spinless circuits, a controlled - $R_z(\theta)$ on qubits `(control, target)` is decomposed into two diagonal fermionic unitaries:
$$U_{CRZ}(\theta) = exp\left(-i \frac{\theta}{2} n_{control}\right) exp\left(i \theta n_{control} n_{target}\right).$$
- For spinful circuits, it applies a half-angle number interaction on …
=> Qiskit gates: Support CCZGate and CRZGate

python/ffsim/qiskit/sim.py, tests/python/qiskit/sim_test.py
Part of #369 
This PR adds support for Qiskit’s `CSGate` and `CSdgGate` to the fermionic simulator. 
Added unit-tests accordingly.
- For spinless circuits, two qubit indices $(i,j)$ mapped to spatial orbitals. Thils applies
$$U_{\mathrm{CS}} = \exp\left(i\tfrac{\pi}{2}n_in_j\right).$$
- For spinful circuits, each qubit index is mapped to either the α‑ or β‑spin sector.  The gate applies
$$U_{\mathrm{CS}}
= \exp\left(i\tfrac{\pi}{2}\prod_{p\in S_\alpha}n_{\alpha,p}
\prod_{q\in S_\beta}n_{\beta,q}\right).$$
- For spinless circuits, the adjoint controlled‑ $S$ gate applies a conditional phase of $-i$.  This is realized by
$$U_{\mathrm{CS^\dagger}}
= \exp\left(-i\tfrac{\pi}{2}n_in_j\right).$$
- For spinful circuits, using the same mapping of qubits to $(S_\alpha,S_\beta)$ as above, the gate …
=> Qiskit gates: Support CSGate and CSdgGate

tests/python/qiskit/sim_test.py
In https://github.com/qiskit-community/ffsim/pull/428/files#r2240082155 I requested that the order of the pairs be shuffled, but it doesn't actually matter if we're doing all pairs anyway, since diagonal gates commute. To test that the phase is correct, we should pick a random subset of pairs each time.
=> Fix phase randomization in Qiskit tests

python/ffsim/qiskit/sim.py, tests/python/qiskit/sim_test.py
Part of #369 
This PR adds support for Qiskit’s `DiagonalGate` to the fermionic simulator.
Added unit-tests accordingly.
For `norb` spatial orbitals with a fixed number of electrons `nocc`, the simulator recognizes `DiagonalGate(diag)` acting on a subset of qubits `i_1, …, i_k`. If the many‑fermion state is
$$|\psi\rangle = \sum_\nu c_\nu |\nu \rangle,$$
where $\nu\in\lbrace0,1\rbrace^{n_{orb}}$ has exactly `nocc` ones, the diagonal gate multiplies each amplitude by a phase from `diag`:
$$c\prime_{\nu} = \lambda_{r(\nu)} c_\nu, \qquad r(\nu)=\sum^k_{p=1} \nu_{i_p}2^{p-1}.$$
Here $r(\nu)$ encodes the occupation bits of $\nu$ at the selected qubit indices.
For `norb` spatial orbitals and spin-resolved electron numbers, `nelec = (nα, nβ)`, the simulator uses `2*norb` qubits, arranged as …
=> Qiskit gates: Support DiagonalGate

.github/workflows/build-and-release.yml, .github/workflows/test-latest-versions.yml, pyproject.toml
Builds wheel for linux aarch64
- example scenario: Running Ubuntu containers on macOS (apple silicon)
- avoids longer build time, requirement for tools, on a linux aarch64 system
Fixes: #476
Note: replaces earlier PR #475
Approach
- Adds a matrix build using the Ubuntu 24.04 arm github runner
- QEMU is an alternative, but more complexity to manage & slow
- Uses a new manylinux (based on AlmaLinux 9) image for aarch64 only
- existing x86_64 left untouched
- problems experienced getting dependencies on centos 7 based distro
Testing
- Build/CI only
- Run on fork: https://github.com/planetf1/ffsim/actions/runs/17799758526 (without pypi publish)
- Local install
Was able to install within `docker run -it ubuntu /bin/sh` on macOS silicon. Checked arch was aarch64, then unzipped the artifact …
=> Build wheels for linux aarch64
