qiskit-community/ffsim

- python/ffsim/gates/gates.py
- tests/gates/gates_test.py
for consistency with occupied_orbitals argument of slater_determinant
> refactor target_orbs argument of apply_num_op_prod_interaction

- python/ffsim/gates/orbital_rotation.py
- python/ffsim/linalg/__init__.py
- python/ffsim/linalg/givens.py
- tests/linalg/givens_test.py
Fixes #31 .
Removes `ffsim.linalg.givens_matrix`
> use zrotg to compute givens rotations

- docs/tutorials/04-lucj.ipynb
> update lucj tutorial to use stretched ethene

- python/ffsim/states/states.py
- tests/states/states_test.py
- tests/trotter/qdrift_test.py
> add orbital_rotation argument to slater determinant one rdm

- python/ffsim/states/wick.py
> use opt einsum contract for wick

- python/ffsim/contract/num_op_sum.py
- python/ffsim/hamiltonians/double_factorized_hamiltonian.py
- python/ffsim/hamiltonians/molecular_hamiltonian.py
- tests/hamiltonians/double_factorized_hamiltonian_test.py
> implement linear operator protocol for df hamiltonian

- python/ffsim/__init__.py
- python/ffsim/variational/__init__.py
- python/ffsim/variational/ucj.py
- tests/variational/ucj_test.py
> add real-valued ucj operator

- python/ffsim/gates/orbital_rotation.py
- tests/gates/orbital_rotation_test.py
> switch givens rotation orbital rotation to slower python code to work around bug

- .github/workflows/check.yml
- .github/workflows/docs.yml
- tox.ini
> add python 3.12

- python/ffsim/hamiltonians/double_factorized_hamiltonian.py
- python/ffsim/linalg/double_factorized_decomposition.py
- tests/linalg/double_factorized_decomposition_test.py
For consistency with UCJOperator
> use diag coulomb indices instead of diag coulomb mask

- python/ffsim/operators/__init__.py
- python/ffsim/operators/fermion_operator.py
- tests/python/operators/fermion_operator_test.py
> Add Fermion operator mapping methods

- Dockerfile
- README.md
- compose.yaml
Adapted from https://github.com/Qiskit-Extensions/circuit-knitting-toolbox
> Add Dockerfile, compose.yaml, and usage instructions

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
Github workflow copied from https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/3838c7c3b45cf7b292854143da4112c7801cc34b/.github/workflows/docker.yml
> add dockerignore and simplify dockerfile, and test in CI

- CONTRIBUTING.md
- README.md
- docs/index.md
- docs/install.md
- Reorganize README and index.html
- Create CONTRIBUTING.md
> refactor docs

- docs/how-to-guides/entanglement-forging.ipynb
> docs: flesh out entanglement forging guide

- python/ffsim/molecular_data.py
- tests/python/molecular_data_test.py
> use MOLPRO table from pyscf

- python/ffsim/qiskit/merge_orbital_rotations.py
- python/ffsim/qiskit/orbital_rotation.py
- python/ffsim/qiskit/slater_determinant.py
- python/ffsim/qiskit/ucj.py
- tests/python/qiskit/merge_orbital_rotations_test.py
- tests/python/qiskit/orbital_rotation_test.py
- tests/python/qiskit/slater_determinant_test.py
also updates slater determinant to store separate orbital rotations
> accept tuple of orbital rotations in qiskit gate instead of spin

- python/ffsim/qiskit/merge_orbital_rotations.py
- python/ffsim/qiskit/slater_determinant.py
- tests/python/qiskit/merge_orbital_rotations_test.py
> update MergeOrbitalRotations to handle Slater determinants

- python/ffsim/gates/diag_coulomb.py
- python/ffsim/gates/orbital_rotation.py
- python/ffsim/qiskit/gates/diag_coulomb.py
- python/ffsim/qiskit/gates/orbital_rotation.py
- tests/python/gates/diag_coulomb_test.py
- tests/python/gates/orbital_rotation_test.py
- tests/python/qiskit/diag_coulomb_test.py
- tests/python/qiskit/orbital_rotation_test.py
> support numpy array input instead of tuple

- docs/how-to-guides/qiskit-sampler.ipynb
- python/ffsim/__init__.py
- python/ffsim/linalg/__init__.py
- python/ffsim/linalg/double_factorized_decomposition.py
- python/ffsim/qiskit/__init__.py
- python/ffsim/qiskit/gates/__init__.py
- python/ffsim/qiskit/gates/ucj_open_shell.py
- python/ffsim/qiskit/sim.py
- python/ffsim/qiskit/transpiler_stages.py
- python/ffsim/random/__init__.py
- python/ffsim/random/random.py
- python/ffsim/variational/__init__.py
- python/ffsim/variational/ucj.py
- python/ffsim/variational/ucj_open_shell.py
- tests/python/linalg/double_factorized_decomposition_test.py
- tests/python/qiskit/merge_orbital_rotations_test.py
- tests/python/qiskit/sampler_test.py
- tests/python/qiskit/ucj_open_shell_test.py
- tests/python/random_test.py
- tests/python/variational/ucj_open_shell_test.py
> Add open-shell UCJ operator

- python/ffsim/gates/orbital_rotation.py
- python/ffsim/states/states.py
- tests/python/gates/orbital_rotation_test.py
> support spinless orbital rotation

- .github/workflows/check.yml
- Cargo.toml
- pyproject.toml
- python/ffsim/cistring.py
- python/ffsim/gates/orbital_rotation.py
- python/ffsim/qiskit/sim.py
- python/ffsim/qiskit/util.py
- python/ffsim/states/states.py
- python/ffsim/testing/testing.py
- python/ffsim/variational/ucj.py
- python/ffsim/variational/ucj_spin_balanced.py
- python/ffsim/variational/ucj_spin_unbalanced.py
- python/ffsim/variational/ucj_spinless.py
- tests/python/contract/num_op_sum_test.py
- tests/python/linalg/givens_test.py
- tox.ini
> Drop Python 3.8

- .github/workflows/check.yml
- .github/workflows/docs-dev.yml
- .github/workflows/docs-release.yml
- .github/workflows/docs-stable.yml
- pyproject.toml
- tests/python/operators/fermion_operator_test.py
> Support Python 3.13

- docs/how-to-guides/qiskit-sampler.ipynb
Among other changes, demonstrates support for some gates from Qiskit's circuit library.
> Update Qiskit Sampler notebook

- python/ffsim/qiskit/sampler.py
- python/ffsim/qiskit/sim.py
- tests/python/qiskit/sim_test.py
> Qiskit gates: Add SwapGate and support XXPlusYYGate between non-adjacent qubit pairs

- python/ffsim/qiskit/sim.py
- tests/python/qiskit/sim_test.py
> Qiskit gates: Support iSwap

- python/ffsim/qiskit/sim.py
- tests/python/qiskit/sim_test.py
> Qiskit gates: Support Z, S, Sdg, T, Tdg

- python/ffsim/qiskit/sim.py
- tests/python/qiskit/sim_test.py
> Qiskit gates: Support CZGate

- python/ffsim/hamiltonians/diagonal_coulomb_hamiltonian.py
- tests/python/hamiltonians/diagonal_coulomb_hamiltonian_test.py
- Check that constant term is real when initializing from FermionOperator
- Add `_approx_eq_` method
- Simplify tests
> Some improvements to DiagonalCoulombHamiltonian

- .github/workflows/test-latest-versions.yml
- .github/workflows/test-minimum-versions.yml
- pyproject.toml
> CI: test minimum versions

- python/ffsim/random/random.py
> improve random UCJ operator generation

- python/ffsim/__init__.py
- python/ffsim/_slow/fermion_operator.py
- python/ffsim/dimensions.py
- python/ffsim/hamiltonians/diagonal_coulomb_hamiltonian.py
- python/ffsim/hamiltonians/double_factorized_hamiltonian.py
- python/ffsim/hamiltonians/molecular_hamiltonian.py
- python/ffsim/hamiltonians/single_factorized_hamiltonian.py
- python/ffsim/protocols/linear_operator_protocol.py
- python/ffsim/qiskit/util.py
- python/ffsim/states/__init__.py
- python/ffsim/states/slater.py
- python/ffsim/states/states.py
To prevent later circular imports
> move dim and dims to top-level file

- .github/workflows/test-latest-versions.yml
- .github/workflows/test-minimum-versions.yml
- CONTRIBUTING.md
- Cargo.toml
- pyproject.toml
- tox.ini
ffsim no longer supports Python 3.9
> Drop Python 3.9
